matrix:
  include:
    - PHP_VERSION: 7.3.4
    - PHP_VERSION: 7.2.17

clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  chown: # we need to do this since our test container runs with www-data and drone clones with root
    image: debian:stretch-slim
    commands:
      - chown -R www-data:www-data /drone/src

  publish-php-image:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/php-runtime
    username: presslabs+drone
    dockerfile: Dockerfile
    build_args:
      - PHP_VERSION=${PHP_VERSION}
    target: php
    cache_from: quay.io/presslabs/php-runtime:testing-${DRONE_BRANCH}-${PHP_VERSION}
    tags: ["testing-${DRONE_BRANCH}-${PHP_VERSION}"]
    custom_labels:
      - quay.expires-after=7d
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: push

  test:
    image: quay.io/presslabs/php-runtime:testing-${DRONE_BRANCH}-${PHP_VERSION}
    pull: true # allways pull the latest tag
    environment:
      - DB_TEST_HOST=database
      - DB_TEST_USER=wordpress
      - DB_TEST_NAME=wordpress_tests
      - DB_TEST_PASSWORD=not-so-secure-but-good-for-ci
      - MEMCACHED_TEST_HOST=memcache:11211
      - UPLOADS_FTP_HOST_TEST=ftp:2121
      - COMPOSER_HOME=/drone/src/.composer
    commands:
      - composer install --no-ansi --prefer-dist
      - make lint
      - make test ARGS="--stop-on-failure"
    when:
      event: push

  publish-wordpress-image:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/wordpress-runtime
    username: presslabs+drone
    dockerfile: Dockerfile
    build_args:
      - PHP_VERSION=${PHP_VERSION}
    target: wordpress
    cache_from: quay.io/presslabs/php-runtime:testing-${DRONE_BRANCH}-${PHP_VERSION}
    tags: ["${DRONE_BRANCH%%-branch}-${PHP_VERSION}-latest", "${DRONE_BRANCH%%-branch}-${PHP_VERSION}-r${DRONE_BUILD_NUMBER}"]
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: push

  publish-composer-package:
    image: quay.io/presslabs/bfc
    environment:
      - GIT_USER=presslabs-bot
      - GIT_EMAIL=bot@presslabs.com
      - RELEASE_UPSTREAM=https://github.com/presslabs/stack-wordpress-release
    secrets: [GIT_PASSWORD]
    commands:
      - setup-credentials-helper.sh
      - ./hack/publish branch ${DRONE_BRANCH%%-branch}
    when:
      event: push
      branch:
        include: ['*-branch']

  publish-composer-package:
    image: quay.io/presslabs/bfc
    environment:
      - GIT_USER=presslabs-bot
      - GIT_EMAIL=bot@presslabs.com
      - RELEASE_UPSTREAM=https://github.com/presslabs/stack-wordpress-release
    secrets: [GIT_PASSWORD]
    commands:
      - setup-credentials-helper.sh
      - ./hack/publish tag ${DRONE_TAG}
    when:
      event: tag

services:
  database:
    image: percona:5.7
    pull: true
    environment:
      - MYSQL_DATABASE=wordpress_tests
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=not-so-secure-but-good-for-ci
      - MYSQL_ROOT_PASSWORD=insecure-root-password-but-good-for-ci

  memcache:
    image: memcached:1.5.10-alpine

  ftp:
    image: quay.io/presslabs/rclone
    command: serve ftp .rclone-ftp --addr=0.0.0.0:2121
    healthcheck:
      test: ["CMD", "nc", "127.0.0.1", "2121"]
      interval: 2s
      timeout: 10s
      retries: 5
