#!/bin/bash
# Copyright 2018 Pressinfra SRL.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e
set -o pipefail

test -d "${DOCUMENT_ROOT:-/var/www/site/web}" || mkdir -p "${DOCUMENT_ROOT:-/var/www/site/web}"
chown "${WORKER_USER:-www-data}:${WORKER_GROUP:-www-data}" "${DOCUMENT_ROOT:-/var/www/site/web}" || true

test -d "${DOCUMENT_ROOT:-/var/www/site/web}/wp-content" || mkdir -p "${DOCUMENT_ROOT:-/var/www/site/web}/wp-content"
chown "${WORKER_USER:-www-data}:${WORKER_GROUP:-www-data}" "${DOCUMENT_ROOT:-/var/www/site/web}/wp-content" || true

for d in themes plugins mu-plugins uploads upgrade ; do
    test -d "${DOCUMENT_ROOT:-/var/www/site/web}/wp-content/$d" || mkdir -p "${DOCUMENT_ROOT:-/var/www/site/web}/wp-content/$d"
    chown "${WORKER_USER:-www-data}:${WORKER_GROUP:-www-data}" "${DOCUMENT_ROOT:-/var/www/site/web}/wp-content/$d" || true
done
