- name: "exif"
- name: "gd"
  build:
    args:
      - "--with-freetype-dir=/usr/include/"
      - "--with-jpeg-dir=/usr/include/"
      - "--with-png-dir=/usr/include/"
      - "--with-webp-dir=/usr/include/"
    depends:
      - libfreetype6-dev
      - libjpeg62-turbo-dev
      - libpng-dev
      - libwebp-dev
- name: imap
  build:
    depends:
      - "libc-client-dev"
      - "libkrb5-dev"
    args:
      - "--with-kerberos"
      - "--with-imap-ssl"
- name: intl
  build:
    depends:
      - "libicu-dev"
      - "zlib1g-dev"
- name: gettext
- name: mysqli
- name: opcache
- name: pcntl
- name: shmop
- name: xmlrpc
- name: xsl
  build:
    depends:
      - "libxslt-dev"
- name: zip
  build:
    depends:
      - "libzip-dev"
      - "zlib1g-dev"

#
# PECL extensions
#

# Install mcrypt for backward compatibility
- name: mcrypt
  version: 1.0.2
  type: pecl
  build:
    depends:
      - "libmcrypt-dev"

# install serializers to make them available for the rest of the extensions
- name: igbinary
  type: pecl
  version: 3.0.1

- name: mailparse
  type: pecl
  version: 3.0.3
- name: memcached
  type: pecl
  version: 3.1.3
  build:
    depends:
      - "libmemcached-dev"
      - "zlib1g-dev"
    args:
      - "--enable-memcached-igbinary"
      - "--enable-memcached-json"
- name: opencensus
  type: pecl
  version: 0.2.2
